const combinations = [
  {
    gender: "feminino",
    ocasion: "formal",
    tshirt: "social_tons_claros",
    pants: "social_tons_neutros",
    shoes: "salto_alto_preto_nude",
  },
  {
    gender: "feminino",
    ocasion: "formal",
    tshirt: "vestido nas cores branca ou preta",
    pants: "sem",
    shoes: "salto alto em preto ou nude",
  },
  {
    gender: "feminino",
    ocasion: "casual",
    tshirt: "camiseta básica em cores vibrantes",
    pants: "calça jeans em tom médi ou escuro",
    shoes: "tênis branco ou preto",
  },
  {
    gender: "feminino",
    ocasion: "esporte",
    tshirt: "camiseta de tecido leve e em tons vibrantes",
    pants: "Shorts ou calça legging em tons claros ou pastel",
    shoes: "tênis preto",
  },
  {
    gender: "feminino",
    ocasion: "casual",
    tshirt: "cropped em cores vibrantes ou básicas",
    pants: "short jeans em tom médio ou escuro",
    shoes: "tênis branco ou preto",
  },
  {
    gender: "feminino",
    ocasion: "festa",
    tshirt: "vestido_curto_tons_vibrantes",
    pants: "nenhum",
    shoes: "salto_alto_tons_metálicos",
  },
  {
    gender: "feminino",
    ocasion: "festa",
    tshirt: "vestido_longo_tons_vibrantes",
    pants: "nenhum",
    shoes: "salto_alto_tons_metálicos",
  },
  {
    gender: "feminino",
    ocasion: "praia",
    tshirt: "vestido de praia em tecido leve e cores claras",
    pants: "sem",
    shoes: "chinelo",
  },
  {
    gender: "masculino",
    ocasion: "formal",
    tshirt: "social_tons_claros_pastel",
    pants: "social_tons_neutros",
    shoes: "social_preto_marrom",
  },
  {
    gender: "masculino",
    ocasion: "formal",
    tshirt: "social_tons_claros_pastel_com_blazer",
    pants: "social_tons_neutros",
    shoes: "social_preto_marrom",
  },
  {
    gender: "masculino",
    ocasion: "casual",
    tshirt: "basica_cores_vibrantes",
    pants: "jeans_medio_escuro",
    shoes: "tênis_preto_branco",
  },
  {
    gender: "masculino",
    ocasion: "casual",
    tshirt: "tecido_leve_tons_vibrantes",
    pants: "bermuda_jeans_medio_escuro",
    shoes: "tênis_preto_branco",
  },
  {
    gender: "masculino",
    ocasion: "esporte",
    tshirt: "camiseta_tecido_leve",
    pants: "bermuda_jeans_medio_escuro",
    shoes: "tênis_preto_branco",
  },
  {
    gender: "masculino",
    ocasion: "festa",
    tshirt: "camiseta_botao_tons_vibrante",
    pants: "calca_jeans",
    shoes: "tenis_neutro",
  },
  {
    gender: "masculino",
    ocasion: "festa",
    tshirt: "camisa_social_tons_vibrantes",
    pants: "calca_social_tom_neutro",
    shoes: "sapato_social",
  },
  {
    gender: "masculino",
    ocasion: "festa",
    tshirt: "camisa_social_tons_vibrantes",
    pants: "calca_social_tom_neutro",
    shoes: "sapato_social",
  },
  {
    gender: "masculino",
    ocasion: "praia",
    tshirt: "nenhum",
    pants: "sunga",
    shoes: "chinelo",
  },
  {
    gender: "masculino",
    ocasion: "praia",
    tshirt: "nenhum",
    pants: "bermuda_tecido_leve_cores_claras",
    shoes: "chinelo",
  },
  {
    gender: "masculino",
    ocasion: "praia",
    tshirt: "camiseta_cores_vibrantes_estampadas",
    pants: "bermuda_tecido_leve_cores_claras",
    shoes: "chinelo",
  },
];

module.exports = {
  combinations,
};
