const combinations = [
  {
    gender: "female",
    ocasion: "formal",
    tshirt: "camisa_social_tons_claros_pastel",
    pants: "social_tons_neutros",
    shoes: "salto_alto_preto_nude",
  },
  {
    gender: "female",
    ocasion: "formal",
    tshirt: "vestido_longo_branco_preto",
    pants: "nenhum",
    shoes: "salto_alto_preto_nude",
  },
  {
    gender: "female",
    ocasion: "casual",
    tshirt: "camisa_basica_cores_vibrantes",
    pants: "short_jeans_tom_medio_escuro",
    shoes: "tenis_branco_preto",
  },
  {
    gender: "female",
    ocasion: "casual",
    tshirt: "camisa_basica_cores_vibrantes",
    pants: "calca_jeans_tom_medio_escuro",
    shoes: "tenis_branco_preto",
  },
  {
    gender: "female",
    ocasion: "casual",
    tshirt: "cropped_cores_vibrantes_basicas",
    pants: "calca_jeans_tom_medio_escuro",
    shoes: "tenis_branco_preto",
  },
  {
    gender: "female",
    ocasion: "casual",
    tshirt: "cropped_cores_vibrantes_basicas",
    pants: "short_jeans_tom_medio_escuro",
    shoes: "tenis_branco_preto",
  },
  {
    gender: "female",
    ocasion: "esporte",
    tshirt: "camiseta_tecido_leve_tons_vibrantes",
    pants: "shorts_legging_tons_claros_pastel",
    shoes: "tenis_branco_preto",
  },
  {
    gender: "female",
    ocasion: "esporte",
    tshirt: "camiseta_tecido_leve_tons_vibrantes",
    pants: "calca_legging_tons_claros_pastel",
    shoes: "tenis_branco_preto",
  },
  {
    gender: "female",
    ocasion: "festa",
    tshirt: "vestido_curto_tons_vibrantes",
    pants: "nenhum",
    shoes: "salto_alto_tons_metálicos",
  },
  {
    gender: "female",
    ocasion: "festa",
    tshirt: "vestido_longo_tons_vibrantes",
    pants: "nenhum",
    shoes: "salto_alto_tons_metálicos",
  },
  {
    gender: "female",
    ocasion: "praia",
    tshirt: "vestido_praia_tecido_leve_cores_claras",
    pants: "nenhum",
    shoes: "chinelo",
  },
  {
    gender: "female",
    ocasion: "praia",
    tshirt: "biquini_cor_basica",
    pants: "biquini_cor_basica",
    shoes: "chinelo",
  },
  {
    gender: "male",
    ocasion: "formal",
    tshirt: "camisa_social_tons_claros_pastel",
    pants: "calca_social_tons_neutros",
    shoes: "sapato_social_preto_marrom",
  },
  {
    gender: "male",
    ocasion: "formal",
    tshirt: "camisa_social_tons_claros_pastel_com_blazer",
    pants: "calca_social_tons_neutros",
    shoes: "sapato_social_preto_marrom",
  },
  {
    gender: "male",
    ocasion: "formal",
    tshirt: "camisa_social_tons_claros_pastel",
    pants: "calca_social_tons_escuro",
    shoes: "sapato_social_preto_marrom",
  },
  {
    gender: "male",
    ocasion: "formal",
    tshirt: "camisa_social_tons_claros_pastel_com_blazer",
    pants: "calca_social_tons_escuro",
    shoes: "sapato_social_preto_marrom",
  },
  {
    gender: "male",
    ocasion: "casual",
    tshirt: "camisa_basica_cores_vibrantes",
    pants: "calca_jeans_medio_escuro",
    shoes: "tenis_branco_preto",
  },
  {
    gender: "male",
    ocasion: "casual",
    tshirt: "camisa_basica_cores_vibrantes",
    pants: "bermuda_jeans_medio_escuro",
    shoes: "tenis_branco_preto",
  },
  {
    gender: "male",
    ocasion: "casual",
    tshirt: "camisa_tecido_leve_tons_vibrantes",
    pants: "bermuda_jeans_medio_escuro",
    shoes: "tenis_branco_preto",
  },
  {
    gender: "male",
    ocasion: "casual",
    tshirt: "camisa_tecido_leve_tons_vibrantes",
    pants: "calca_jeans_medio_escuro",
    shoes: "tenis_branco_preto",
  },
  {
    gender: "male",
    ocasion: "esporte",
    tshirt: "camiseta_tecido_leve",
    pants: "bermuda_tecido_leve_medio_escuro",
    shoes: "tenis_branco_preto",
  },
  {
    gender: "male",
    ocasion: "esporte",
    tshirt: "camisa_tecido_leve_tons_vibrantes",
    pants: "bermuda_tecido_leve_medio_escuro",
    shoes: "tenis_branco_preto",
  },
  {
    gender: "male",
    ocasion: "esporte",
    tshirt: "camiseta_tecido_leve",
    pants: "bermuda_tecido_leve_tons_claros",
    shoes: "tenis_branco_preto",
  },
  {
    gender: "male",
    ocasion: "esporte",
    tshirt: "camisa_tecido_leve_tons_vibrantes",
    pants: "bermuda_tecido_leve_tons_claros",
    shoes: "tenis_branco_preto",
  },
  {
    gender: "male",
    ocasion: "festa",
    tshirt: "camiseta_botao_tons_vibrante",
    pants: "calca_jeans_medio_escuro",
    shoes: "tenis_neutro",
  },
  {
    gender: "male",
    ocasion: "festa",
    tshirt: "camiseta_botao_cores_vibrante",
    pants: "calca_social_tons_neutros",
    shoes: "sapato_social_preto_marrom",
  },
  {
    gender: "male",
    ocasion: "festa",
    tshirt: "camiseta_botao_cores_vibrante",
    pants: "calca_jeans_medio_escuro",
    shoes: "sapato_social_preto_marrom",
  },
  {
    gender: "male",
    ocasion: "festa",
    tshirt: "camiseta_botao_cores_vibrante",
    pants: "calca_jeans_medio_escuro",
    shoes: "tenis_neutro",
  },
  {
    gender: "male",
    ocasion: "festa",
    tshirt: "camiseta_botao_cores_vibrante",
    pants: "calca_jeans_medio_escuro",
    shoes: "tenis_branco_preto",
  },
  {
    gender: "male",
    ocasion: "festa",
    tshirt: "camiseta_botao_cores_vibrante",
    pants: "calca_jeans_medio_escuro",
    shoes: "tenis_branco_preto",
  },
  {
    gender: "male",
    ocasion: "praia",
    tshirt: "nenhum",
    pants: "sunga",
    shoes: "chinelo",
  },
  {
    gender: "male",
    ocasion: "praia",
    tshirt: "nenhum",
    pants: "bermuda_tecido_leve_tons_claros",
    shoes: "chinelo",
  },
  {
    gender: "male",
    ocasion: "praia",
    tshirt: "camiseta_cores_vibrantes_estampadas",
    pants: "bermuda_tecido_leve_tons_claros",
    shoes: "chinelo",
  },
];

module.exports = {
  combinations,
};
